### ISSUE TITLE
missing schematic for V2.5.2

### ISSUE THREAD

**Issue by messschuh** [charleslemaire0/TeenAstroHardware#1]
Hi Charles, 
i can´t find the schematic for the Teenastro Mini 2.5.2.  Can u add it please. 

thx

**Comment by charleslemaire0** [comment]
I would be happy if some one spend time on that...

**Comment by messschuh** [comment]
so u mean it is not available at moment? i allready ordered the PCB for V2.5.2, how u design the layout without a schematic? 
i could try to make one like the earlier versions, but i need some information of the circuit.

**Comment by charleslemaire0** [comment]
Yes that it, I made the design with fritzing and the schematic is hard to
do in fritzing. I will be so happy if we could move to what ever :)
so id one want schematics currently you have to open the Fritzing file and
see how it is wire, it share 90% with the version 2.4.x
Sorry for that but I can't be every where and do my best
Charles

Am Fr., 31. März 2023 um 19:57 Uhr schrieb mm_2² ***@***.***>:

**Comment by messschuh** [comment]
OK no problem.
i never worked with fritzzing but i will have a look to it. who made the older schematics pdf´s which are online, not u? i will try to do it with kicad. 
i had a look to the source code to find the Pin´s for gnss or focuser... i can´t find it, but i´m not really familar with coding. so can u give me an advice where i can find a pinmapping or so?!

**Comment by charleslemaire0** [comment]
pin Mapping for the main unit:
https://github.com/charleslemaire0/TeenAstro/blob/master/TeenAstroMainUnit/Pins.TeenAstro.h
for there is at the moment no focuser for the version 2.5.0 but if you want
to contribute I have already a design in mind and we can have a call to fix
the details
here you can find the fritzing file:
https://github.com/charleslemaire0/TeenAstroHardware/tree/main/pcb

I used the Fritzing version 0.9.3

Am Fr., 31. März 2023 um 20:58 Uhr schrieb mm_2² ***@***.***>:

**Comment by messschuh** [comment]
great, thx. 
the focuser is not my main focus at moment, but  later it would nice to have.  i see there are TX/RX 2 and 3 Pins allready at the board, so  it should be possible to make serial port connection at the mini, to add an external focuser(with additional teensy), right? of course an all in one board solution would be nicer, but for the mini board i see no chance to add an additional stepper driver, unless we made a layout for the tmc2130 only, or take the longer case (FR 80 42 120) and add a focuser board.  
for the moment i have enough input and need look on it. thx  again

**Comment by charleslemaire0** [comment]
it is better if the there is only one Teensy that controls the focuser and
the telescope we save then 35€
The silent TMC5160 are working well and I see no more reason to support the
BOB in future design for the mini.
Then on the board we have 3 Silenstep stick, the focuser will be controlled
only over SPI and can share the spi connection with the telescope SPI

in order to simplify the build, I would be happy if you use this component:
https://secure.reichelt.com/fr/fr/sal-m-8-4-broches-connecteur-femelle-coud--conec-42-01427-p249166.html?&trstct=pol_83&nbc=1
for the connection to the SHC and the encoders (at the back) GRN and 5V at
the same pin number for every connector.
and use this component for the Stepper motors
https://secure.reichelt.com/fr/fr/sal-m-12-4-broches-connecteur-encastrer-coud--conec-43-01204-p249154.html?&trstct=pol_1&nbc=1

If you want you can also place 2 PCB inside the mini. For me it is
important that it is easy to build.

Charles


Am Fr., 31. März 2023 um 21:47 Uhr schrieb mm_2² ***@***.***>:

**Comment by messschuh** [comment]
send a mail to "TeenAstro+owner@groups.io". did u received it?

**Comment by charleslemaire0** [comment]
Any comments?

Am Sa., 1. Apr. 2023 um 11:13 Uhr schrieb Charles Lemaire <
***@***.***>:

**Comment by charleslemaire0** [comment]
No

**Comment by charleslemaire0** [comment]
thanks
https://github.com/charleslemaire0/TeenAstroHardware/blob/main/MainUnit/Mini/V25/Teenastro%20sch%C3%A9ma%20V2.5.2.pdf
